### ISSUE TITLE
Routes

### ISSUE THREAD

**Issue by holytoastr** [jeffreyeaton76/ihavetogo#7]
Need to edit the rails routes to make site more driven by angular routes

**Comment by MaxKaye** [comment]
I can work on this

**Comment by MaxKaye** [comment]
I think you did this here, no?

```
Rails.application.routes.draw do
  resources :toilets do
    resources :comments
  end
```

**Comment by jeffreyeaton76** [comment]
She's talking about the fact that our app will only have one page, so there won't be much use for normal RESTful routes. We'll have to create a RouterFunction which maps all the various .`state`s to the various locations in the app.

**Comment by jeffreyeaton76** [comment]
like:

```
  function RouterFunction($stateProvider){
    $stateProvider
    .state("index", {
      url: "/",
      templateUrl: "toilets.index.html",
      controller: "toiletsCtrl",
      controllerAs: "toiletVM"
    })
```

and so on

**Comment by holytoastr** [comment]
Exactly. Need to change it to those state things.

**Comment by MaxKaye** [comment]
got it- I'm working on it now

**Comment by holytoastr** [comment]
I'll take care of this based on conversation with Robin.

**Comment by holytoastr** [comment]
Done with the rails portion. Closing this issue.
